package com.online.booking.entities;
// Generated Nov 1, 2019 4:41:20 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog")
public class Blog implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String title;
	private String content;
	private boolean status;
	private String src;
	@Temporal(TemporalType.DATE)
	private Date created;
	private Set<Imageblog> imageblogs = new HashSet<Imageblog>(0);

	public Blog() {
	}

	public Blog(Account account, boolean status) {
		this.account = account;
		this.status = status;
	}

	public Blog(Account account, String title, String content, boolean status, Set<Imageblog> imageblogs) {
		this.account = account;
		this.title = title;
		this.content = content;
		this.status = status;
		this.imageblogs = imageblogs;
	}

	public Blog(Integer id, Account account, String title, String content, boolean status, String src, Date created,
			Set<Imageblog> imageblogs) {
		super();
		this.id = id;
		this.account = account;
		this.title = title;
		this.content = content;
		this.status = status;
		this.src = src;
		this.created = created;
		this.imageblogs = imageblogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "title", length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blog")
	public Set<Imageblog> getImageblogs() {
		return this.imageblogs;
	}

	public void setImageblogs(Set<Imageblog> imageblogs) {
		this.imageblogs = imageblogs;
	}

	public String getSrc() {
		return src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
