package com.online.booking.entities;
// Generated Oct 31, 2019 9:54:37 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CopponHotel generated by hbm2java
 */
@Entity
@Table(name = "coppon_hotel", catalog = "bookinghotel")
public class CopponHotel implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private String name;
	private Double sale;
	private boolean status;

	public CopponHotel() {
	}

	public CopponHotel(String name, boolean status) {
		this.name = name;
		this.status = status;
	}

	public CopponHotel(String name, Double sale, boolean status) {
		this.name = name;
		this.sale = sale;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sale", precision = 22, scale = 0)
	public Double getSale() {
		return this.sale;
	}

	public void setSale(Double sale) {
		this.sale = sale;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
