package com.online.booking.entities;
// Generated Nov 8, 2019 11:57:35 AM by Hibernate Tools 5.1.10.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotEmpty;

import org.hibernate.annotations.NotFound;
import org.hibernate.validator.constraints.Length;
import org.springframework.lang.NonNullFields;
import org.springframework.web.bind.annotation.Mapping;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel")

public class Hotel implements java.io.Serializable {
	
	private Integer id;

	private Account accountByIdAcEmployee;

	private Account accountByAccountId;
	
	private CopponHotel copponHotel;

	private StarRating starRating;
	@NotEmpty
	@Length(max = 250)
	private String name;
	private String image;
	private String description;
	private String addressFull;
	private String ward;
	private String city;
	private String provincial;
	private String country;
	private Boolean wifi;
	private Boolean parking;
	private Boolean spa;
	private Boolean gym;
	private Boolean carRental;
	private Boolean airportTransfer;
	private Boolean freeBreakfast;
	private Boolean swimmingPool;
	private Boolean elevator;
	private Boolean receptionist;
	private Boolean airConditioner;
	private Boolean freeCancellation;
	private Boolean payAtHotel;
	private Boolean assemblyFacilites;
	private Boolean driveway;
	private boolean status;
	

	private List<Room> rooms = new ArrayList<Room>(0);

	private Set<ServiceHotel> serviceHotels = new HashSet<ServiceHotel>(0);

	private List<Evaluate> evaluates = new ArrayList<Evaluate>(0);
	
	
	public Hotel() {
	
		
	}
	

	public Hotel(Integer id) {
		super();
		this.id = id;
	}


	public Hotel(Account accountByAccountId, StarRating starRating, String city, String country, boolean status) {
		this.accountByAccountId = accountByAccountId;
		this.starRating = starRating;
		this.city = city;
		this.country = country;
		this.status = status;
	}



	public Hotel(Integer id, Account accountByIdAcEmployee, Account accountByAccountId, CopponHotel copponHotel,
			StarRating starRating, String name, String image, String description, String addressFull, String ward,
			String city, String provincial, String country, Boolean wifi, Boolean parking, Boolean spa, Boolean gym,
			Boolean carRental, Boolean airportTransfer, Boolean freeBreakfast, Boolean swimmingPool, Boolean elevator,
			Boolean receptionist, Boolean airConditioner, Boolean freeCancellation, Boolean payAtHotel,
			Boolean assemblyFacilites, Boolean driveway, boolean status, List<Room> rooms,
			Set<ServiceHotel> serviceHotels, List<Evaluate> evaluates) {
		super();
		this.id = id;
		this.accountByIdAcEmployee = accountByIdAcEmployee;
		this.accountByAccountId = accountByAccountId;
		this.copponHotel = copponHotel;
		this.starRating = starRating;
		this.name = name;
		this.image = image;
		this.description = description;
		this.addressFull = addressFull;
		this.ward = ward;
		this.city = city;
		this.provincial = provincial;
		this.country = country;
		this.wifi = wifi;
		this.parking = parking;
		this.spa = spa;
		this.gym = gym;
		this.carRental = carRental;
		this.airportTransfer = airportTransfer;
		this.freeBreakfast = freeBreakfast;
		this.swimmingPool = swimmingPool;
		this.elevator = elevator;
		this.receptionist = receptionist;
		this.airConditioner = airConditioner;
		this.freeCancellation = freeCancellation;
		this.payAtHotel = payAtHotel;
		this.assemblyFacilites = assemblyFacilites;
		this.driveway = driveway;
		this.status = status;
		this.rooms = rooms;
		this.serviceHotels = serviceHotels;
		this.evaluates = evaluates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ac_employee")
	
	public Account getAccountByIdAcEmployee() {
		return this.accountByIdAcEmployee;
	}

	public void setAccountByIdAcEmployee(Account accountByIdAcEmployee) {
		this.accountByIdAcEmployee = accountByIdAcEmployee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccountByAccountId() {
		return this.accountByAccountId;
	}

	public void setAccountByAccountId(Account accountByAccountId) {
		this.accountByAccountId = accountByAccountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_coppon_hotel")

	public CopponHotel getCopponHotel() {
		return this.copponHotel;
	}

	public void setCopponHotel(CopponHotel copponHotel) {
		this.copponHotel = copponHotel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "starrating_id", nullable = false)
	
	public StarRating getStarRating() {
		return this.starRating;
	}

	public void setStarRating(StarRating starRating) {
		this.starRating = starRating;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "address_full", length = 500)
	public String getAddressFull() {
		return this.addressFull;
	}

	public void setAddressFull(String addressFull) {
		this.addressFull = addressFull;
	}
	
	@Column(name = "ward", length = 50)
	public String getWard() {
		return ward;
	}

	public void setWard(String ward) {
		this.ward = ward;
	}

	@Column(name = "city", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "provincial", length = 50)
	public String getProvincial() {
		return this.provincial;
	}

	public void setProvincial(String provincial) {
		this.provincial = provincial;
	}

	@Column(name = "country", nullable = false, length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "wifi")
	public Boolean getWifi() {
		return this.wifi;
	}

	public void setWifi(Boolean wifi) {
		this.wifi = wifi;
	}

	@Column(name = "parking")
	public Boolean getParking() {
		return this.parking;
	}

	public void setParking(Boolean parking) {
		this.parking = parking;
	}

	@Column(name = "spa")
	public Boolean getSpa() {
		return this.spa;
	}

	public void setSpa(Boolean spa) {
		this.spa = spa;
	}

	@Column(name = "gym")
	public Boolean getGym() {
		return this.gym;
	}

	public void setGym(Boolean gym) {
		this.gym = gym;
	}

	@Column(name = "car_rental")
	public Boolean getCarRental() {
		return this.carRental;
	}

	public void setCarRental(Boolean carRental) {
		this.carRental = carRental;
	}

	@Column(name = "airport_transfer")
	public Boolean getAirportTransfer() {
		return this.airportTransfer;
	}

	public void setAirportTransfer(Boolean airportTransfer) {
		this.airportTransfer = airportTransfer;
	}

	@Column(name = "free_breakfast")
	public Boolean getFreeBreakfast() {
		return this.freeBreakfast;
	}

	public void setFreeBreakfast(Boolean freeBreakfast) {
		this.freeBreakfast = freeBreakfast;
	}

	@Column(name = "swimming_pool")
	public Boolean getSwimmingPool() {
		return this.swimmingPool;
	}

	public void setSwimmingPool(Boolean swimmingPool) {
		this.swimmingPool = swimmingPool;
	}

	@Column(name = "elevator")
	public Boolean getElevator() {
		return this.elevator;
	}

	public void setElevator(Boolean elevator) {
		this.elevator = elevator;
	}

	@Column(name = "receptionist")
	public Boolean getReceptionist() {
		return this.receptionist;
	}

	public void setReceptionist(Boolean receptionist) {
		this.receptionist = receptionist;
	}

	@Column(name = "air_conditioner")
	public Boolean getAirConditioner() {
		return this.airConditioner;
	}

	public void setAirConditioner(Boolean airConditioner) {
		this.airConditioner = airConditioner;
	}

	@Column(name = "free_cancellation")
	public Boolean getFreeCancellation() {
		return this.freeCancellation;
	}

	public void setFreeCancellation(Boolean freeCancellation) {
		this.freeCancellation = freeCancellation;
	}

	@Column(name = "pay_at_hotel")
	public Boolean getPayAtHotel() {
		return this.payAtHotel;
	}

	public void setPayAtHotel(Boolean payAtHotel) {
		this.payAtHotel = payAtHotel;
	}

	@Column(name = "assembly_facilites")
	public Boolean getAssemblyFacilites() {
		return this.assemblyFacilites;
	}

	public void setAssemblyFacilites(Boolean assemblyFacilites) {
		this.assemblyFacilites = assemblyFacilites;
	}

	@Column(name = "driveway")
	public Boolean getDriveway() {
		return this.driveway;
	}

	public void setDriveway(Boolean driveway) {
		this.driveway = driveway;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")

	public List<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(List<Room> rooms) {
		this.rooms = rooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")

	public Set<ServiceHotel> getServiceHotels() {
		return this.serviceHotels;
	}

	public void setServiceHotels(Set<ServiceHotel> serviceHotels) {
		this.serviceHotels = serviceHotels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotel")
	
	public List<Evaluate> getEvaluates() {
		return this.evaluates;
	}

	public void setEvaluates(List<Evaluate> evaluates) {
		this.evaluates = evaluates;
	}

	@Override
	public String toString() {
		return "Hotel [id=" + id + ", accountByIdAcEmployee=" + accountByIdAcEmployee + ", accountByAccountId="
				+ accountByAccountId + ", copponHotel=" + copponHotel + ", starRating=" + starRating.getAmount() + ", name=" + name
				+ ", image=" + image + ", description=" + description + ", addressFull=" + addressFull + ", ward="
				+ ward + ", city=" + city + ", provincial=" + provincial + ", country=" + country + ", wifi=" + wifi
				+ ", parking=" + parking + ", spa=" + spa + ", gym=" + gym + ", carRental=" + carRental
				+ ", airportTransfer=" + airportTransfer + ", freeBreakfast=" + freeBreakfast + ", swimmingPool="
				+ swimmingPool + ", elevator=" + elevator + ", receptionist=" + receptionist + ", airConditioner="
				+ airConditioner + ", freeCancellation=" + freeCancellation + ", payAtHotel=" + payAtHotel
				+ ", assemblyFacilites=" + assemblyFacilites + ", driveway=" + driveway + ", status=" + status
				+ ", rooms=" + rooms + ", serviceHotels=" + serviceHotels + ", evaluates=" + evaluates + "]";
	}

	

}
