package com.online.booking.entities;
// Generated Oct 31, 2019 9:54:37 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "bookinghotel")
public class Payment implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private Orders orders;
	private ServiceHotel serviceHotel;
	private String name;
	private String paymentcode;
	private boolean status;

	public Payment() {
	}

	public Payment(boolean status) {
		this.status = status;
	}

	public Payment(Orders orders, ServiceHotel serviceHotel, String name, String paymentcode, boolean status) {
		this.orders = orders;
		this.serviceHotel = serviceHotel;
		this.name = name;
		this.paymentcode = paymentcode;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_order")
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_service_hotel")
	public ServiceHotel getServiceHotel() {
		return this.serviceHotel;
	}

	public void setServiceHotel(ServiceHotel serviceHotel) {
		this.serviceHotel = serviceHotel;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "paymentcode", length = 250)
	public String getPaymentcode() {
		return this.paymentcode;
	}

	public void setPaymentcode(String paymentcode) {
		this.paymentcode = paymentcode;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
