package com.online.booking.entities;
// Generated Nov 1, 2019 4:41:20 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ReasonReport generated by hbm2java
 */
@Entity
@Table(name = "reason_report")
public class ReasonReport implements java.io.Serializable {

	private int id;
	private String content;
	private boolean status;
	private Set<Report> reports = new HashSet<Report>(0);

	public ReasonReport() {
	}

	public ReasonReport(int id, String content, boolean status) {
		this.id = id;
		this.content = content;
		this.status = status;
	}

	public ReasonReport(int id, String content, boolean status, Set<Report> reports) {
		this.id = id;
		this.content = content;
		this.status = status;
		this.reports = reports;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reasonReport")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
