package com.online.booking.entities;
// Generated Oct 31, 2019 9:54:37 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name = "sale", catalog = "bookinghotel", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Sale implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private Account account;
	private String code;
	private String description;
	private double sales;
	private Date startday;
	private Date endday;
	private boolean status;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Sale() {
	}

	public Sale(String code, double sales, boolean status) {
		this.code = code;
		this.sales = sales;
		this.status = status;
	}

	public Sale(Account account, String code, String description, double sales, Date startday, Date endday,
			boolean status, Set<Orders> orderses) {
		this.account = account;
		this.code = code;
		this.description = description;
		this.sales = sales;
		this.startday = startday;
		this.endday = endday;
		this.status = status;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "code", unique = true, nullable = false, length = 250)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sales", nullable = false, precision = 22, scale = 0)
	public double getSales() {
		return this.sales;
	}

	public void setSales(double sales) {
		this.sales = sales;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startday", length = 10)
	public Date getStartday() {
		return this.startday;
	}

	public void setStartday(Date startday) {
		this.startday = startday;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endday", length = 10)
	public Date getEndday() {
		return this.endday;
	}

	public void setEndday(Date endday) {
		this.endday = endday;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sale")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
