package com.online.booking.entities;
// Generated Oct 31, 2019 9:54:37 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "bookinghotel")
public class Service implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private Account account;
	private Servicetype servicetype;
	private String name;
	private Long price;
	private String core;
	private int priority;
	private String iconSrc;
	private String description;
	private boolean status;
	private Set<ServiceHotel> serviceHotels = new HashSet<ServiceHotel>(0);

	public Service() {
	}

	public Service(Account account, Servicetype servicetype, int priority, boolean status) {
		this.account = account;
		this.servicetype = servicetype;
		this.priority = priority;
		this.status = status;
	}

	public Service(Account account, Servicetype servicetype, String name, Long price, String core, int priority,
			String iconSrc, String description, boolean status, Set<ServiceHotel> serviceHotels) {
		this.account = account;
		this.servicetype = servicetype;
		this.name = name;
		this.price = price;
		this.core = core;
		this.priority = priority;
		this.iconSrc = iconSrc;
		this.description = description;
		this.status = status;
		this.serviceHotels = serviceHotels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_account", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	public Servicetype getServicetype() {
		return this.servicetype;
	}

	public void setServicetype(Servicetype servicetype) {
		this.servicetype = servicetype;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "core", length = 10)
	public String getCore() {
		return this.core;
	}

	public void setCore(String core) {
		this.core = core;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "icon_src", length = 50)
	public String getIconSrc() {
		return this.iconSrc;
	}

	public void setIconSrc(String iconSrc) {
		this.iconSrc = iconSrc;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<ServiceHotel> getServiceHotels() {
		return this.serviceHotels;
	}

	public void setServiceHotels(Set<ServiceHotel> serviceHotels) {
		this.serviceHotels = serviceHotels;
	}

}
